"use client";

import { FiCheckCircle, FiClock, FiFileText, FiLock, FiShield, FiXCircle } from "react-icons/fi";
import { motion } from "motion/react";
import { ErrorCallout } from "@/components/ui/ErrorCallout";
import { usePrefersReducedMotion } from "@/components/tabs/usePrefersReducedMotion";
import type { AgreementTimelineEventResponse } from "@/lib/tabs/types";

type AgreementTimelineProps = { events: AgreementTimelineEventResponse[]; error?: boolean; onRetry: () => void };
const icons = { tab_created: FiFileText, expense_added: FiFileText, expense_confirmed: FiCheckCircle, expense_disputed: FiXCircle, final_tab_created: FiFileText, final_tab_locked: FiLock, member_authorized: FiShield, authorization_revoked: FiXCircle, authorization_expired: FiClock, settlement_submitted: FiClock, settlement_confirmed: FiCheckCircle, settlement_failed: FiXCircle };
export function AgreementTimeline({ events, error = false, onRetry }: AgreementTimelineProps) { const reducedMotion = usePrefersReducedMotion(); return <section aria-labelledby="agreement-timeline-heading" className="grid gap-4"><div><h2 id="agreement-timeline-heading" className="text-xl font-semibold text-foreground">Agreement timeline</h2><p className="mt-1 text-sm leading-6 text-muted">The milestones that explain how this Final Tab moved forward.</p></div>{error ? <ErrorCallout action={<button className="text-sm font-semibold text-primary underline" onClick={onRetry} type="button">Try again</button>} message="We could not load the agreement timeline. Try again." /> : events.length ? <ol className="grid gap-0">{events.map((event, index) => { const Icon = icons[event.kind]; return <motion.li animate={{ opacity: 1 }} className="grid grid-cols-[1.5rem_minmax(0,1fr)] gap-3" initial={reducedMotion ? false : { opacity: 0 }} key={event.id} transition={{ delay: reducedMotion ? 0 : index * 0.02 }}><div className="flex flex-col items-center"><Icon aria-hidden="true" className="mt-1 text-primary" />{index < events.length - 1 ? <span aria-hidden="true" className="my-1 min-h-6 w-px bg-outline-variant" /> : null}</div><div className="pb-4"><p className="text-sm font-medium leading-6 text-foreground">{event.message}</p><time className="text-xs text-muted" dateTime={event.occurredAt}>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.occurredAt))}</time></div></motion.li>; })}</ol> : <p className="rounded-md border border-outline-variant bg-surface-container-low px-4 py-3 text-sm leading-6 text-muted">The agreement timeline will appear as your group reviews this tab.</p>}</section>; }
